/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "box_3.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>


void print_box(dimensions dims, box_results *b_res, mail_dims m_dims, float *price)
{
    printf("A box with dimensions:\nLength: %.2f\nWidth: %.2f\nHeight: %.2f\n",
           dims.length, dims.width, dims.height);
    printf("Has a surface area of: %.2f\n", b_res->surface);
    printf("Has Volume of: %.2f\n", m_dims.volume);
    printf("Has mass of: %.2f\n", m_dims.mass);
    printf("Post cost is: $%.2f\n", *price);
    return;
}

void print_box_2(mail_dims m_dims, float *price)
{
    printf("Has Volume of: %.2f\n", m_dims.volume);
    printf("Has mass of: %.2f\n", m_dims.mass);
    printf("Post cost is: $%.2f\n", *price);
    return;
}

int main (int argc, char *argv[])
{
    CLIENT *c_handle;
    dimensions dims;
    box_results *b_res;
    mail_dims m_dims;
    float *price;

    if (argc != 4 && argc != 6) {
        printf("usage: %s remote_host Volume mass\n", argv[0]);
        printf("Or usage: %s remote_host length width height mass\n", argv[0]);
        exit(EXIT_FAILURE);
    }

    /* Create a connection handle to make rpc’s */
    c_handle = clnt_create(argv[1], RPC_BOX, BOXVERSION2, "udp");
    if (c_handle == NULL)
    {
        clnt_pcreateerror(argv[1]);
        exit(EXIT_FAILURE);
    }

    if(argc == 4){
        m_dims.volume = atof(argv[2]);
        m_dims.mass = atof(argv[3]);
        price = mail_calc_2(&m_dims, c_handle);
        if (price == NULL)
        {
            clnt_perror(c_handle, argv[1]);
            exit(EXIT_FAILURE);
        }
        print_box_2(m_dims, price);

        clnt_destroy(c_handle);

        return 0;
    }

    if(argc == 6){
        dims.length = atof(argv[2]);
        dims.width = atof(argv[3]);
        dims.height = atof(argv[4]);

        b_res = box_calc_2(&dims, c_handle);
        if (b_res == NULL)
        {
            clnt_perror(c_handle, argv[1]);
            exit(EXIT_FAILURE);
        }

        m_dims.volume = b_res->volume;
        m_dims.mass = atof(argv[5]);

        price = mail_calc_2(&m_dims, c_handle);
        if (price == NULL)
        {
            clnt_perror(c_handle, argv[1]);
            exit(EXIT_FAILURE);
        }
        print_box(dims, b_res, m_dims, price);

        clnt_destroy(c_handle);

        return 0;
    }

}
