/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "box_2.h"

box_results *
box_calc_2_svc(dimensions *argp, struct svc_req *rqstp)
{
	static box_results  result;

	/*
	 * insert server code here
	 */

	return &result;
}

float *
mail_calc_2_svc(mail_dims *argp, struct svc_req *rqstp)
{
	static float  result;

	/*
	 * insert server code here
	 */

	return &result;
}
