/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "box.h"

box_results *
box_calc_1_svc(dimensions *argp, struct svc_req *rqstp)
{
	static box_results  result;

	/*
	 * insert server code here
	 */

	return &result;
}
