/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "box.h"


void print_box(float l, float w, float h, float sa, float v)
{
    printf("A box with dimensions:\nLength: %.2f\nWidth: %.2f\nHeight: %.2f\n", l, w, h);
    printf("Has a surface area of: %.2f\n", sa);
    printf("And volume of %.2f\n", v);
    return;
}


int main(int argc, char* argv[])
{
    CLIENT *c_handle;
    dimensions dims;
    box_results *res;

    if (argc != 5)
    {
        printf("Usage: %s remote_host length width height\n", argv[0]);
        exit(EXIT_FAILURE);
    }

    dims.length = atof(argv[2]);
    dims.width = atof(argv[3]);
    dims.height = atof(argv[4]);

    /* Create a connection handle to make rpc’s */
    c_handle = clnt_create(argv[1], RPC_BOX, BOXVERSION1, "udp");
    if (c_handle == NULL)
    {
        clnt_pcreateerror(argv[1]);
        exit(EXIT_FAILURE);
    }

    /* Make the RPC */
    res = box_calc_1(&dims, c_handle);
    if (res == NULL) {
        clnt_perror(c_handle, argv[1]);
        exit(EXIT_FAILURE);
    }

    print_box(dims.length, dims.width, dims.height, res->surface, res->volume);
    /* free up the RPC handle */
    clnt_destroy(c_handle);

    return 0;
}